import jsPDF from "jspdf";
import { SummaryOutput } from "@/lib/summarizers";

export interface ExportPayload {
  documentName: string;
  summaryData: SummaryOutput;
}

/**
 * Formats plain text for clipboard and .txt exports
 */
export function formatPlainTextSummary({
  documentName,
  summaryData,
}: ExportPayload): string {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const divider = "=".repeat(65);
  const subDivider = "-".repeat(65);

  let content = `${divider}\n`;
  content += `DOCUMIND SMART SUMMARY REPORT\n`;
  content += `${divider}\n\n`;
  content += `Document Name:       ${documentName}\n`;
  content += `Generated Date:      ${dateStr}\n`;
  content += `Summary Preset:      ${summaryData.length.toUpperCase()} (~${
    summaryData.length === "short"
      ? "100"
      : summaryData.length === "medium"
      ? "250"
      : "500"
  } words)\n`;
  content += `Summarization Engine: ${
    summaryData.engine === "gemini"
      ? "Gemini AI Flash"
      : "Extractive Offline Engine"
  }\n`;
  content += `Word Count:          ${summaryData.originalWordCount} words -> ${summaryData.summaryWordCount} words (${summaryData.reductionPercentage}% reduction)\n\n`;

  content += `${subDivider}\n`;
  content += `EXECUTIVE SUMMARY\n`;
  content += `${subDivider}\n\n`;
  content += `${summaryData.summary}\n\n`;

  if (summaryData.keyTakeaways && summaryData.keyTakeaways.length > 0) {
    content += `${subDivider}\n`;
    content += `KEY POINTS & MAIN IDEAS\n`;
    content += `${subDivider}\n\n`;
    summaryData.keyTakeaways.forEach((point, index) => {
      content += `${index + 1}. ${point}\n\n`;
    });
  }

  content += `${divider}\n`;
  content += `Generated by DocuMind - Document Summary Assistant\n`;
  content += `${divider}\n`;

  return content;
}

/**
 * Formats structured Markdown for .md export
 */
export function formatMarkdownSummary({
  documentName,
  summaryData,
}: ExportPayload): string {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# DocuMind Smart Summary\n\n`;
  md += `## Document: **${documentName}**\n\n`;
  md += `| Attribute | Details |\n`;
  md += `| :--- | :--- |\n`;
  md += `| **Date** | ${dateStr} |\n`;
  md += `| **Preset** | \`${summaryData.length.toUpperCase()}\` |\n`;
  md += `| **Engine** | ${
    summaryData.engine === "gemini" ? "Gemini AI Flash" : "Extractive Offline Engine"
  } |\n`;
  md += `| **Original Words** | ${summaryData.originalWordCount} words |\n`;
  md += `| **Summary Words** | **${summaryData.summaryWordCount} words** |\n`;
  md += `| **Condensation** | **${summaryData.reductionPercentage}% reduction** |\n\n`;

  md += `---\n\n`;
  md += `### 📄 Executive Summary\n\n`;
  md += `${summaryData.summary}\n\n`;

  if (summaryData.keyTakeaways && summaryData.keyTakeaways.length > 0) {
    md += `---\n\n`;
    md += `### 💡 Key Points & Main Ideas\n\n`;
    summaryData.keyTakeaways.forEach((point, index) => {
      md += `${index + 1}. **${point}**\n`;
    });
    md += `\n`;
  }

  md += `---\n`;
  md += `*Generated automatically by [DocuMind](https://github.com) Document Summary Assistant.*`;

  return md;
}

/**
 * Copies summary content directly to user clipboard
 */
export async function copySummaryToClipboard(
  payload: ExportPayload
): Promise<boolean> {
  try {
    const text = formatPlainTextSummary(payload);
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    // Fallback for older browsers
    const textarea = document.createElement("textarea");
    textarea.value = text;
    textarea.style.position = "fixed";
    textarea.style.opacity = "0";
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand("copy");
    document.body.removeChild(textarea);
    return success;
  } catch (err) {
    console.error("Clipboard copy failed:", err);
    return false;
  }
}

/**
 * Triggers a file download in the browser for given content
 */
function triggerDownload(
  blob: Blob,
  filename: string
) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Downloads summary formatted as .txt file
 */
export function downloadTxtSummary(payload: ExportPayload): void {
  const content = formatPlainTextSummary(payload);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const baseName = payload.documentName.replace(/\.[^/.]+$/, "");
  triggerDownload(blob, `${baseName}-summary.txt`);
}

/**
 * Downloads summary formatted as .md file
 */
export function downloadMarkdownSummary(payload: ExportPayload): void {
  const content = formatMarkdownSummary(payload);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const baseName = payload.documentName.replace(/\.[^/.]+$/, "");
  triggerDownload(blob, `${baseName}-summary.md`);
}

/**
 * Generates and downloads a clean, styled multi-page PDF document
 */
export function downloadPdfSummary(payload: ExportPayload): void {
  const { documentName, summaryData } = payload;
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  // Header Banner
  doc.setFillColor(79, 70, 229); // Indigo 600
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("DocuMind Smart Summary", margin, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    `Generated on ${new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    })}`,
    margin,
    21
  );

  y = 38;

  // Document Metadata Box
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.roundedRect(margin, y, contentWidth, 24, 2, 2, "FD");

  doc.setTextColor(30, 41, 59); // Slate 800
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(`Document: ${documentName}`, margin + 5, y + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105); // Slate 600
  doc.text(
    `Preset: ${summaryData.length.toUpperCase()}  |  Engine: ${
      summaryData.engine === "gemini" ? "Gemini AI Flash" : "Extractive Engine"
    }  |  Words: ${summaryData.originalWordCount} -> ${
      summaryData.summaryWordCount
    } (${summaryData.reductionPercentage}% reduction)`,
    margin + 5,
    y + 16
  );

  y += 34;

  // Function to check and add new page if needed
  const checkPageBreak = (neededSpace: number) => {
    if (y + neededSpace > pageHeight - margin) {
      doc.addPage();
      y = 20;
    }
  };

  // Section 1: Executive Summary
  checkPageBreak(25);
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Executive Summary", margin, y);
  y += 3;

  doc.setDrawColor(79, 70, 229);
  doc.setLineWidth(0.7);
  doc.line(margin, y, margin + 40, y);
  y += 6;

  doc.setTextColor(51, 65, 85); // Slate 700
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);

  const paragraphs = summaryData.summary.split("\n\n");
  for (const para of paragraphs) {
    const lines = doc.splitTextToSize(para, contentWidth);
    const blockHeight = lines.length * 4.8;
    checkPageBreak(blockHeight + 4);
    doc.text(lines, margin, y);
    y += blockHeight + 4;
  }

  y += 4;

  // Section 2: Key Points & Main Ideas
  if (summaryData.keyTakeaways && summaryData.keyTakeaways.length > 0) {
    checkPageBreak(30);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Key Points & Main Ideas", margin, y);
    y += 3;

    doc.setDrawColor(16, 185, 129); // Emerald 500
    doc.setLineWidth(0.7);
    doc.line(margin, y, margin + 45, y);
    y += 7;

    summaryData.keyTakeaways.forEach((point, index) => {
      const bulletPrefix = `${index + 1}.  `;
      const fullText = `${bulletPrefix}${point}`;
      const lines = doc.splitTextToSize(fullText, contentWidth - 4);
      const blockHeight = lines.length * 4.8;

      checkPageBreak(blockHeight + 3);

      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(241, 245, 249);
      doc.roundedRect(margin, y - 3, contentWidth, blockHeight + 3, 1.5, 1.5, "FD");

      doc.setTextColor(30, 41, 59);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.text(lines, margin + 3, y + 1);

      y += blockHeight + 5;
    });
  }

  // Footer on all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.setFontSize(8);
    doc.text(
      `DocuMind Document Summary Assistant  |  Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  const baseName = documentName.replace(/\.[^/.]+$/, "");
  doc.save(`${baseName}-summary.pdf`);
}
