import { PDFParse } from "pdf-parse";

export interface ExtractionResult {
  success: boolean;
  text: string;
  pageCount: number;
  wordCount: number;
  characterCount: number;
  readingTimeMinutes: number;
  metadata?: {
    title?: string;
    author?: string;
    creationDate?: string;
    producer?: string;
    formatVersion?: string;
  };
  isScanned: boolean;
  requiresOcr: boolean;
  message: string;
}

/**
 * Normalizes extracted PDF text, preserving logical paragraphs and formatting
 */
export function cleanPdfText(rawText: string): string {
  if (!rawText) return "";

  return rawText
    // Remove page footer markers generated by pdf-parse (e.g. "-- 1 of 1 --")
    .replace(/--\s*\d+\s+of\s+\d+\s*--/gi, "")
    // Standardize line endings
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    // Replace non-breaking spaces with standard space
    .replace(/\u00A0/g, " ")
    // Fix hyphenated line breaks (e.g., "re- \nport" -> "report")
    .replace(/(\w+)-\s*\n\s*(\w+)/g, "$1$2")
    // Replace 3+ consecutive newlines with 2 newlines (clean paragraph breaks)
    .replace(/\n{3,}/g, "\n\n")
    // Trim each line
    .split("\n")
    .map((line) => line.trim())
    .join("\n")
    .trim();
}

/**
 * Extracts text and metadata from a PDF Buffer server-side
 */
export async function extractPdf(buffer: Buffer): Promise<ExtractionResult> {
  try {
    const parser = new PDFParse({ data: buffer });
    const textResult = await parser.getText();
    const rawText = textResult?.text || "";
    const pageCount = textResult?.total || (textResult?.pages ? textResult.pages.length : 1);

    let metadata: any = {};
    try {
      const infoResult = await parser.getInfo();
      if (infoResult?.info) {
        metadata = {
          title: infoResult.info.Title || undefined,
          author: infoResult.info.Author || undefined,
          creationDate: infoResult.info.CreationDate ? String(infoResult.info.CreationDate) : undefined,
          producer: infoResult.info.Producer || undefined,
          formatVersion: infoResult.info.PDFFormatVersion || undefined,
        };
      }
    } catch {
      // Info extraction is optional
    }

    const cleanedText = cleanPdfText(rawText);

    // Calculate statistics
    const words = cleanedText ? cleanedText.split(/\s+/).filter(Boolean) : [];
    const wordCount = words.length;
    const characterCount = cleanedText.length;
    const readingTimeMinutes = Math.max(1, Math.ceil(wordCount / 200));

    // Detect scanned / image-only PDFs
    const isScanned = wordCount < 15;
    const requiresOcr = isScanned;

    let message = `Successfully extracted ${wordCount} words across ${pageCount} ${
      pageCount === 1 ? "page" : "pages"
    }.`;

    if (isScanned) {
      message =
        "Little or no selectable text detected. This document appears to be a scanned PDF. OCR will be required in Phase 4.";
    }

    return {
      success: true,
      text: cleanedText,
      pageCount,
      wordCount,
      characterCount,
      readingTimeMinutes,
      metadata,
      isScanned,
      requiresOcr,
      message,
    };
  } catch (error: any) {
    const errorMessage = error?.message || "Unknown error during PDF extraction";
    return {
      success: false,
      text: "",
      pageCount: 0,
      wordCount: 0,
      characterCount: 0,
      readingTimeMinutes: 0,
      isScanned: false,
      requiresOcr: false,
      message: `Failed to parse PDF document: ${errorMessage}. The file may be corrupt or encrypted.`,
    };
  }
}
