// @ts-ignore
import pdfParse from "pdf-parse";

export interface ExtractionResult {
  success: boolean;
  text: string;
  pageCount: number;
  wordCount: number;
  characterCount: number;
  readingTimeMinutes: number;
  metadata?: {
    title?: string;
    author?: string;
    creationDate?: string;
    producer?: string;
    formatVersion?: string;
  };
  isScanned: boolean;
  requiresOcr: boolean;
  message: string;
}

/**
 * Fallback stream text extractor for PDFs with non-standard XRef tables or stream compression
 */
function extractPdfStreamFallback(buffer: Buffer): string {
  try {
    const raw = buffer.toString("latin1");
    let text = "";

    // Match text within standard PDF Text Object blocks (BT ... ET)
    const btBlocks = raw.match(/BT[\s\S]*?ET/g) || [];
    for (const block of btBlocks) {
      // Match (text) Tj
      const tjMatches = block.match(/\((.*?)\)\s*Tj/g) || [];
      for (const tj of tjMatches) {
        const m = tj.match(/\((.*?)\)\s*Tj/);
        if (m && m[1]) {
          text += m[1] + " ";
        }
      }

      // Match [(text)] TJ arrays
      const bigTjMatches = block.match(/\[(.*?)\]\s*TJ/g) || [];
      for (const bigTj of bigTjMatches) {
        const innerStrings = bigTj.match(/\((.*?)\)/g) || [];
        for (const str of innerStrings) {
          text += str.slice(1, -1) + " ";
        }
      }
      text += "\n";
    }

    return text.replace(/\\([()\\])/g, "$1").trim();
  } catch {
    return "";
  }
}

/**
 * Normalizes extracted PDF text, preserving logical paragraphs and formatting
 */
export function cleanPdfText(rawText: string): string {
  if (!rawText) return "";

  return rawText
    // Remove page footer markers generated by pdf-parse (e.g. "-- 1 of 1 --")
    .replace(/--\s*\d+\s+of\s+\d+\s*--/gi, "")
    // Standardize line endings
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    // Replace non-breaking spaces with standard space
    .replace(/\u00A0/g, " ")
    // Fix hyphenated line breaks (e.g., "re- \nport" -> "report")
    .replace(/(\w+)-\s*\n\s*(\w+)/g, "$1$2")
    // Replace 3+ consecutive newlines with 2 newlines (clean paragraph breaks)
    .replace(/\n{3,}/g, "\n\n")
    // Trim each line
    .split("\n")
    .map((line) => line.trim())
    .join("\n")
    .trim();
}

/**
 * Extracts text and metadata from a PDF Buffer server-side
 * Pure JavaScript implementation with 0 native dependencies and resilient stream fallback
 */
export async function extractPdf(buffer: Buffer): Promise<ExtractionResult> {
  let rawText = "";
  let pageCount = 1;
  let metadata: any = {};

  // Strategy 1: Primary parser (pdf-parse)
  try {
    const data = await pdfParse(buffer);
    if (data?.text && data.text.trim().length > 0) {
      rawText = data.text;
      pageCount = data.numpages || 1;
      if (data.info) {
        metadata = {
          title: data.info.Title || undefined,
          author: data.info.Author || undefined,
          creationDate: data.info.CreationDate ? String(data.info.CreationDate) : undefined,
          producer: data.info.Producer || undefined,
          formatVersion: data.version || undefined,
        };
      }
    }
  } catch (primaryError: any) {
    // If primary parser fails (e.g., bad XRef entries), fallback to stream extraction
    console.warn("Primary PDF parse failed, trying stream fallback:", primaryError?.message);
  }

  // Strategy 2: Stream fallback if primary returned empty or threw an error
  if (!rawText.trim()) {
    const fallbackText = extractPdfStreamFallback(buffer);
    if (fallbackText) {
      rawText = fallbackText;
    }
  }

  const cleanedText = cleanPdfText(rawText);

  // Calculate statistics
  const words = cleanedText ? cleanedText.split(/\s+/).filter(Boolean) : [];
  const wordCount = words.length;
  const characterCount = cleanedText.length;
  const readingTimeMinutes = Math.max(1, Math.ceil(wordCount / 200));

  // Detect scanned / image-only PDFs
  const isScanned = wordCount < 15;
  const requiresOcr = isScanned;

  let message = `Successfully extracted ${wordCount} words across ${pageCount} ${
    pageCount === 1 ? "page" : "pages"
  }.`;

  if (isScanned) {
    message =
      "Little or no selectable text detected. This document appears to be a scanned PDF. OCR will be required for full recognition.";
  }

  return {
    success: true,
    text: cleanedText,
    pageCount,
    wordCount,
    characterCount,
    readingTimeMinutes,
    metadata,
    isScanned,
    requiresOcr,
    message,
  };
}
